allowBuilds:
  '@sentry/cli': true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.65.2'
  - '@sveltejs/kit@2.70.0'
